USE demo;
go
CREATE TABLE Types
(
	Id INT NOT NULL IDENTITY(1,1),
	data NVARCHAR(50) NULL,
	parent INT NOT NULL DEFAULT(0)
)
GO
ALTER TABLE Types ADD CONSTRAINT PK_Types PRIMARY KEY(Id)


USE demo;
ALTER TABLE dbo.Types ADD firstchild INT NOT NULL DEFAULT(0)
ALTER TABLE dbo.Types ADD rightsib INT NOT NULL DEFAULT(0)
